server:
  port: 8080

spring:
  application:
    name: looky

  # 업로드 제한
  servlet:
    multipart:
      max-file-size: 50MB    # 개별 파일 용량
      max-request-size: 50MB # 요청 전체 용량

  #  문서화 (Swagger)
  springdoc:
    swagger-ui:
      path: /docs
    api-docs:
      path: /v3/api-docs
    show-actuator: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json

  # 클라우드 설정
  cloud:
    aws:
      s3:
        bucket: ${BUCKET_NAME}
      region: ap-northeast-2
      credentials:
        access-key: ${IAM_ACCESS_KEY}
        secret-key: ${IAM_SECRET_KEY}

# JWT 정책
jwt:
  secret: ${JWT_SECRET}
  access-expiration: 3600000
  refresh-expiration: 1209600000



# open api 설정
open-api:
  service-key: ${OPEN_API_KEY}

# Naver Maps API
naver:
  maps:
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}